### ISSUE TITLE
Error: Unable to retrieve the collateral from the Intel SGX PCS

### ISSUE THREAD

**Issue by hustliyilin** [intel/confidential-computing.tee.dcap.pccs#33]
I refer to [this guide](https://software.intel.com/content/www/us/en/develop/articles/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html) to subscribe to the Intel PCS and set up the Intel PCCS. However, when I run pccs typing this command

```shell
node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js
```

and there is an error like
```shell
# node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js
morgan deprecated default format: use combined format node_modules/esm/esm.js:1:278827
2020-12-24 17:29:16.015 [info]: HTTPS Server is running on: https://localhost:8081
2020-12-24 17:29:23.337 [info]: Request-ID is : cca33f9e55bc4d21be1ad4f02eb6bd12
2020-12-24 17:29:23.338 [error]: Error: Unable to retrieve the collateral from the Intel SGX PCS.
    at do_request (/opt/intel/sgx-dcap-pccs/pcs_client/pcs_client.js:70:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

and I run QuoteGenerationSample with error code 0xe044
```shell
# ./app
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe044
```

Could you help me? Thanks a lot

**Comment by bgotowal** [comment]
This issue has been transferred from DCAP project, following PCCS detach to a dedicated GitHub project.

Original URL: https://github.com/intel/confidential-computing.tee.dcap/issues/153
